INSTALL updated

diff --git a/INSTALL b/INSTALL
--- a/INSTALL
+++ b/INSTALL
@@ -2,17 +2,24 @@
 #
 # Install all .sh script files by putting symlinks into a destination directory (default is users's ~/bin dir)
 
-DST=~/bin
+DESTINATIONDIR=~/bin
 
 # Not more thank one parameter is allowed
 if [ $# -gt 1 ] ; then
-    echo "usage: $0 [<destination directory, default: $DST)>]"
+    echo "usage: $0 [<destination directory, default: $DESTINATIONDIR)>]"
     exit 1
+fi
+
+# A way to clean up again
+if [[ $1 == "--remove" ]] ; then
+  SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" #set the variable to the place where script is loaded from
+  find $DESTINATIONDIR -lname "$SCRIPTDIR/*" -delete
+  exit 2
 fi
 
 # If no parameter is given, destination directory is set to default
 if [ $# -eq 1 ] ; then
-    DST=$1
+    DESTINATIONDIR=$1
 fi
 
 # Make symbolic links to all .sh files in directory
@@ -21,5 +28,5 @@ for f in *.sh ; do
         continue
     fi
     echo "$f"
-    ln -fs "$(realpath "$f")" "$DST/$f"
+    ln -fs "$(realpath "$f")" "$DESTINATIONDIR/$f"
 done
